### ISSUE TITLE
Running into other issue (File not valid) 

### ISSUE THREAD

**Issue by snvoid** [JuanuSt/mmega#5]
Hey man, 

Its been a while since I tried this shell script and i'm running into some new problems this time. Some guidance would be appreciated where I'm going wrong this time. 

I keep getting **File not valid.** 

![image](https://user-images.githubusercontent.com/60519765/84459903-8783e180-ac36-11ea-94dc-f9c3fe31eeb2.png)

This is the command i used: 
`./mmega.sh -c mega.txt -m df`

I created a new config file with just one account to test with the following structures.  

`name,email,password,,/root 
`
also tried
`name,email,password,, 
`
and neither worked. 

i gave execute permission to the .sh script. I didn't really change the files from the time it worked last time but I might be messing something else up. 

Thanks

**Comment by JuanuSt** [comment]
Hi Snvoid, thanks to reporting.

I think the problem is not the format of the configuration file (but use the first option, the remote directory /Root is mandatory).

The problem comes from the 'file' command, used to distinguish between encrypted and plain text files. This command is used on line 361. Can you show me the output of the command `file mega.txt`? On my machine (ubuntu 20.04) the output is: mega.txt: ASCII text. The important part is 'text' (or RSA for encrypted files). If not too much trouble, could you check that the command `file mega.txt | cut -d '  ' -f 3` equals 'text'?

**Comment by snvoid** [comment]
Thank you so much for the quick reply. I was able to get it working. I'm not exactly sure what the issue was since, but this is what i changed to get it working. 

I created a new txt doc on linux. Copied the entire list of email/passwords into a new text document w/o any extensions. My primary OS is Windows and only occasionally use Linux (dual boot) so the .txt file was created via Windows. I wonder if that was the issue because after I created the new file  it worked! I also tried to use sudo before running it but after trying it today w/o it i realized that wasn't it. Seems like the new file did the trick! 

100% user error on my part, but this is definitely a learning experience for me. Also definitely inspired to learn bash now!!! 

However i went ahead and tried the command you suggested in case other people run into the same issue or I do again lol. This might also help me understand what I was doing wrong in the first place.  

**Here is the output for `file mega.txt`**

- `mega.txt: ASCII text, with CRLF line terminators`

**Second command** `file mega.txt | cut -d ' ' -f 3`

- `text,`

Anyway thank you so much for your help. I'm happy to report that things are working again and it was just user error on my part. I'm learning a lot though!

**Comment by JuanuSt** [comment]
Thanks for the output of commands.

It was a good idea to copy the contents of the text file made in Windows, to one made in Linux. The problem is that little comma after 'text,'.

I have modified the script so that it can also recognize such files.
